---
title: "Capital 1"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(encoding = "utf-8")

```

#Intuit Online Case
 This is a group assignment for MKTG482. 
 Group member: Javier Urbina, Ahsan Kamran, Toshi Murakami
 
##Load data and library
```{r}

library(tidyverse)
library(mktg482)
library(nnet)
library(knitr)
library(janitor)
library(readxl)
library(psych)
library(statar)
library(mktg482)
library(tidyverse)
library(sjPlot)
library(AlgDesign)



rm(list=ls())
set.seed(13579)

```
First, we tranform the data and convert categorical variables into factors

```{r}
data1_count<- read_csv("Data1.csv")
data2<- read_csv("Data2.csv")



data1<-uncount(data1_count, `Accounts`)

str(data1)
```


##generate fractional designs 
```{r}
exp.design <- list(APR=c("14.9","16.8","19.8"),
                   Fee=c("0","20"),
                   Rate=c("Fixed","Variable"))
full.design <- expand.grid(exp.design)
full.design
frac.design <-optFederov(data=full.design, nTrials=5)
frac.design$design
```

##Analyzing experimental data
```{r}
lr.data1 <-glm(sale~APR*Fix_Var*Annual_Fee*VISA_MC*BK, data=data1_count, family=binomial)
summary(lr.data1)

#We cannot choose to 
lr.data1 <-glm(sale~APR*Fix_Var*Annual_Fee*VISA_MC*BK, data=data1_count, family=binomial)
summary(lr.data1)

```


```{r}
accounts_lr<-glm(sale~ APR + Date + Annual_Fee + VISA_MC + BK, family=binomial, data=data1)
```


