---
title: "Pentathlon (Part III)"      # Replace with name of assignment
author: 
   - name: Section 32        
   - name: Ahsan Kamran
   - name: Toshi Murakami
   - name: Javier Urbina     
output:
  html_notebook: default
---

# Preliminaries

### Determine notebook defaults:
```{r, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,      # Print all the code in all the chunks
                      warning=FALSE,  # Don't print warning statements
                      message=FALSE,  # Don't print other R output messages
                      comment=NA)     # Helps produce prettier output
```

### Load packages:
```{r, echo=FALSE, message = FALSE, warning = FALSE}
library(gmodels)
library(modelr)
library(janitor)
library(haven)
library(readxl)
library(knitr)
library(psych)
library(statar)
library(tidyverse)
```

### Read in the data:
```{r}
load("PentathlonTargeting.Rdata")

pent <- pent %>% mutate(age=factor(age), female=factor(female), buyer=factor(buyer))

#Now we create the training and testing split

pent.train<- pent%>% filter(training==1)
pent.test<- pent%>% filter(training==0)
```

## Part 1 Analyising the different offers

Type your answer text here, intervowen with blocks of R code

```{r}
# First  we create a logistic regression model for every type of offer ( endurance, backcountry, etc)

lr.backcountry <- glm(buyer ~ age + female + income + education + children+ freq_endurance+freq_strength+freq_water+freq_team+freq_backcountry+freq_winter+freq_racquet,
family=binomial, data=pent.train %>% filter(message=="backcountry"))

pent.test <- pent.test %>%
mutate(pr.backcountry = predict(lr.backcountry, newdata=pent.test, type="response"))
```


And we repeat for every other message

```{r}
# Endurance

lr.endurance <- glm(buyer ~ age + female + income + education + children+ freq_endurance+freq_strength+freq_water+freq_team+freq_backcountry+freq_winter+freq_racquet,
family=binomial, data=pent.train %>% filter(message=="endurance"))

pent.test <- pent.test %>%
mutate(pr.endurance = predict(lr.endurance, newdata=pent.test, type="response"))
```



```{r}
# Strength

lr.strength <- glm(buyer ~ age + female + income + education + children+ freq_endurance+freq_strength+freq_water+freq_team+freq_backcountry+freq_winter+freq_racquet,
family=binomial, data=pent.train %>% filter(message=="strength"))

pent.test <- pent.test %>%
mutate(pr.endurance = predict(lr.strength, newdata=pent.test, type="response"))
```

```{r}
#Water

lr.water <- glm(buyer ~ age + female + income + education + children+ freq_endurance+freq_strength+freq_water+freq_team+freq_backcountry+freq_winter+freq_racquet,
family=binomial, data=pent.train %>% filter(message=="water"))

pent.test <- pent.test %>%
mutate(pr.water = predict(lr.water, newdata=pent.test, type="response"))
```

```{r}
#Team

lr.team <- glm(buyer ~ age + female + income + education + children+ freq_endurance+freq_strength+freq_water+freq_team+freq_backcountry+freq_winter+freq_racquet,
family=binomial, data=pent.train %>% filter(message=="team"))

pent.test <- pent.test %>%
mutate(pr.team = predict(lr.team, newdata=pent.test, type="response"))
```

```{r}
#Winter

lr.winter <- glm(buyer ~ age + female + income + education + children+ freq_endurance+freq_strength+freq_water+freq_team+freq_backcountry+freq_winter+freq_racquet,
family=binomial, data=pent.train %>% filter(message=="winter"))

pent.test <- pent.test %>%
mutate(pr.winter = predict(lr.winter, newdata=pent.test, type="response"))
```

```{r}
#Winter

lr.racquet <- glm(buyer ~ age + female + income + education + children+ freq_endurance+freq_strength+freq_water+freq_team+freq_backcountry+freq_winter+freq_racquet,
family=binomial, data=pent.train %>% filter(message=="racquet"))

pent.test <- pent.test %>%
mutate(pr.racquet = predict(lr.racquet, newdata=pent.test, type="response"))
```

## Question 2
```{r}

pent.test<- pent.test %>%
   mutate(pr.max = pmax(pr.backcountry, pr.endurance, pr.water, pr.team, pr.winter, pr.racquet),
          mail.offer=case_when(
             pr.backcountry==pr.max ~ "Backcountry",
             pr.endurance==pr.max~ "Endurance",
             pr.water==pr.max~ "Water",
             pr.team==pr.max ~ "Team",
             pr.winter==pr.max~ "Winter",
             pr.racquet==pr.max ~ "Racquet"))

pent.test%>% tabyl(mail.offer )


```

## Question 3

Type your answer text here, intervowen with blocks of R code


```{r}
pent.test <- pent.test %>%
  mutate(ep.backcountry=pr.backcountry*total_os*0.4, ep.endurance=pr.endurance*total_os*0.4, ep.racquet=pr.racquet*total_os*0.4, ep.team=pr.team*total_os*0.4, ep.water=pr.water*total_os*0.4, ep.winter=pr.winter*total_os*.4)

pent.test<- pent.test %>%
   mutate(ep.max = pmax(ep.backcountry, ep.endurance, ep.water, ep.team, ep.winter, ep.racquet),
          mail.offer.ep=case_when(
             ep.backcountry==ep.max ~ "Backcountry",
             ep.endurance==ep.max~ "Endurance",
             ep.water==ep.max~ "Water",
             ep.team==ep.max ~ "Team",
             ep.winter==ep.max~ "Winter",
             ep.racquet==ep.max ~ "Racquet"))

pent.test%>% tabyl(mail.offer.ep )







```

