---
title: "S Mobile"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(encoding = "utf-8")

```

#Intuit Online Case
 This is a group assignment for MKTG482. 
 Group member: Javier Urbina, Ahsan Kamran, Toshi Murakami
 
##Load data and library
```{r}

library(tidyverse)
library(mktg482)
library(nnet)
library(knitr)
library(janitor)
library(readxl)
library(psych)
library(statar)
library(mktg482)
library(tidyverse)
library(sjPlot)



rm(list=ls())
set.seed(13579)
load("smobile_churn.Rdata")
```


##Split Data into test and training

```{r}
smobile_training <- smobile %>% filter(training==1)
smobile_test<-smobile %>% filter(training==0)
```

## Develop Model

```{r}
smobile_training_lr<-glm(churn~revenue+mou+overage+roam+changem+changer+dropvce+blckvce+unansvce+custcare+threeway+months+uniqsubs+phones+eqpdays+age+children+creditaa+refurb+occprof+occcler+occcrft+occstud+occhmkr+occret+occself+travel+retcalls+refer+incmiss+income+mcycle,family=binomial, data=smobile_training)

summary(smobile_training_lr)

#Adding Odds Rations
cbind(COEF=coef(smobile_training_lr),confint(smobile_training_lr))
exp(cbind(COEF=coef(smobile_training_lr),confint(smobile_training_lr)))

pred_lr_training<-predict(smobile_training_lr, type="response")
pred_lr_test<-predict(smobile_training_lr,newdata=smobile_test ,type="response")
```

##Predictions
```{r}
pred_lr_training <- predict(smobile_training_lr,data= smobile+training, type="response")
pred_lr_test <- predict(smobile_training_lr, newdata=smobile_test,type="response")
pred_lr_rollout <- predict(smobile_training_lr, newdata=rollout,type="response")
rollout <- rollout %>% 
  mutate(predictions=pred_lr_rollout)

```

## Checking Model Effectiveness
```{r}
gainsplot(pred_lr_test, label.var =smobile_test$res )
gainsplot(pred_lr_training, label.var =smobile_training$res )

```

## Plot Predictions
```{r}
plot_model(smobile_training_lr,type="pred")
```

## Variable Importance
```{r}
varimp.logistic(smobile_training_lr)
```
## Variable Importance Chart
```{r}
varimp.logistic(smobile_training_lr) %>% plotimp.logistic()
# Important Variables [Vr imp >1.40] 
#1. Home-maker occupation 
#2. # of days of current equipment
#3. Crafts occupation
#4. Mean monthly minutes of use
#5. Age
#6. Mean # of blocked calls
#7. Months in service
```

## Avg customer spend over lifetime
```{r}
smobile%>%
  group_by(churn) %>%
  summarise(mean_revenue=mean(revenue))
#Similar monthly spending for both categories
```

## Testing who to target
```{r}
rollouttgt<- rollout%>%
  mutate(eqpdays_ntile=ntile(eqpdays,5),mou_ntile=ntile(mou,5))

mou_eqp.df <-rollouttgt %>%
  group_by(eqpdays_ntile,mou_ntile) %>%
  summarise(mean_pred=mean(predictions),mean_eqpdays=mean(eqpdays),mean_spending=mean(revenue), mean_minutes=mean(mou)
mou_eqp.df

```